import hulpmiddelen
def handleiding():
    background(240)
    textSize(30)
    text("Dit is de digitale handleiding.", width / 2, 50)
    hulpmiddelen.button(0,560,250,60,"#a9a9a9","Klik hier om terug te gaan","#00000",None,20)
    textSize(16)
    text("Je kan huizen en andere gebouwen kopen door middel van de shop.", width/2, 100)
    text("Ze zijn digitaal te zien maar je kunt ze ook", width/2, 120)
    text("op het fysieke bord neerleggen.", width/2, 140)
    text("Via het digitale spel moet je ook je eventkaartjes pakken.", width/2, 170)
    text("Wanneer je gebruik maak van het digitale spel moet je de fysieke", width/2, 190)
    text("eventkaartjes niet meer gebruiken.", width/2, 210) 
    text("Door het digitale component hoef je het fysieke geld, energie", width/2, 240) 
    text("en inwoners niet meer te gebruiken. Dit wordt automatisch", width/2, 260)
    text("bijgehouden bij alles wat je doet. Zodra een speler drie monumenten", width/2, 280)
    text("bezit stopt het spel automatisch en is er een winnaar.", width/2, 300)
    text("Je kan zien dat je aan de beurt ben door het groene balkje bij", width/2, 330)
    text("je naam. Als je klaar bent met je beurt, zal je in het menu op", width/2, 350)
    text("'Beeindig beurt' moeten drukken. Je kan ten alle tijden het", width/2, 370)
    text("spel opnieuw beginnen door in het menu op 'Reset spel' te drukken.", width/2, 390)
    text("Om naar de shop te gaan moet je in het menu op 'Shop' drukken.", width/2, 410)
